### ISSUE TITLE
Wrong template type in wrapping file

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITKGenericLabelInterpolator#10]
The second template type of the class [LabelImageGenericInterpolateImageFunction](https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator/blob/760a1047884d71d1f9f0b0b5a3b7bf67d7394d92/include/itkLabelImageGenericInterpolateImageFunction.h) should be an interpolator ([see test](https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator/blob/760a1047884d71d1f9f0b0b5a3b7bf67d7394d92/test/RotateLabels.cxx#L171))

Currently, the [wrapping file](https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator/blob/760a1047884d71d1f9f0b0b5a3b7bf67d7394d92/wrapping/itkLabelImageGenericInterpolateImageFunction.wrap) uses `double` or `itk::Vector< double,2 >` instead of using an interpolator type.

Compilation errors are visible [on CI](https://travis-ci.org/InsightSoftwareConsortium/ITKGenericLabelInterpolator/builds/533889296?utm_source=github_status&utm_medium=notification)

**Comment by thewtex** [comment]
Resolved via https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator/commit/11616d3bb65c942d405437d0322473797155215c
