### ISSUE TITLE
Update CI configuration

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKGenericLabelInterpolator#33]
Following discussion at https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator/pull/32

- Update to the latest composite action that supports Python packaging
- Re-add `-manylinux2014` wheel generation

**Comment by tbirdso** [comment]
Note that point 2 depends on a fix for [https://github.com/InsightSoftwareConsortium/ITKPythonPackage/issues/203](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/issues/203)

**Comment by tbirdso** [comment]
Closed in https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator/pull/34
